import type {
  AdminArtwork,
  AdminCollector,
  EscrowTransaction,
  AuditLogEntry,
} from "./adminTypes";

export const INITIAL_ADMIN_ARTWORKS: AdminArtwork[] = [
  {
    id: "ART-8921",
    title: "Commemorative Oba Head",
    culture: "Benin Empire (Nigeria)",
    era: "16th Century",
    valuation: 1350000,
    status: "Live",
    tier: "VIP",
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCJ92I1jZERzyaqiKc3FH4C9WCoalLYXn4QtDJIh9ZxMxNszZAyIVEgqplLCo7hV6V2HH7-BoQadYiRfZZ2rRVU2KyFezQYJuPejkEXFZmCocL68oD0FhhmK9qjLDUo_dGaLRJjMVDik4XNPGjB6Oc9qTanNVOjjccILVz6KJ9t75nNkB6_MXRhluItt8QhY_hJT0f1IjvtTbYQtOVAAFWxowRUhcdAARMvXHJ_EcwLFlZ4EPwj2Hy7iJOq7_ZanC7qnp6Kfj7IvA",
    description:
      "A masterfully cast bronze commemorative head of an Oba, featuring intricate beadwork collar and detailed facial scarification marks.",
    provenanceHash: "0x8fae3199...a4b2",
    dateCreated: "2024-01-15",
    acquiredYear: 2021,
    acquiredMethod: "Private Acquisition",
    provenance: [
      "Royal Court of Benin (until 1897)",
      "British Expedition Collection (1897–1934)",
      "Von Habsburg Collection, Vienna (1934–2021)",
      "Aduna Private Trust (2021)",
    ],
  },
  {
    id: "ART-4290",
    title: "Kaddara Terracotta Sculpture",
    culture: "Nok Culture (Nigeria)",
    era: "500 BC",
    valuation: 680000,
    status: "Live",
    tier: "Prestige",
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCKdiuCw_zTP7WHWHB-xQl16JnOkQSri-8ci20nKnR27BCtmwVuwcbwKQIbr9sAAHFv9NYiL4PCGB4-ewMFWqh7AJtgb05jo4DDtZPr3Y9oZHqvI2Af-K3L53NRUz2v71O6aqjDsl0uWhN882QvAtN53NZqRrjYshqHcr4DfCFJJ2CZjzr63Sa4WPzffRH744uT15yF1UP-xw5XfoKjA_UCf2KG91Cj2mhw_EyMNxG6EYYeHWwNoo-KyTIkrXowWo-mtQf0MtOApw",
    description:
      "A rare Nok terracotta figure displaying the characteristic elliptical eyes and sophisticated hollow-fired clay body.",
    provenanceHash: "0x9ca31844...b5c1",
    dateCreated: "2024-03-20",
    acquiredYear: 2023,
    acquiredMethod: "Auction Acquisition",
    provenance: [
      "Archaeological Site, Kaduna State, Nigeria",
      "Private Collection, Lagos (1970–2005)",
      "Christie's London (2005)",
      "Aduna Gallery (2023)",
    ],
  },
  {
    id: "ART-7512",
    title: "Royal Beaded Crown (Ade)",
    culture: "Yoruba Kingdom (Nigeria)",
    era: "19th Century",
    valuation: 420000,
    status: "Draft",
    tier: "VIP",
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBxXscArJs7jm8fkVlA0HIef3hG7nB9zqwOK7BCT6Qu4klQbMUWYQgZqPNbqpJRq-MwcmGhf4mmYLiUVINuSkXR8rBU8F1ZHRF8wchLVhgPk5iAS5xT3kjYy85IbKAaxp70n1aUl_n6zBrAIntKg2Sp49BQ_UhCYts4FHBnX2N1rN3ZdNIZQ5CPx1Y-T76d-vIAr0xDMJeZ_ubf0t8oewNFH_fr-mVjel_xdJ3NupPP1Ijd0IfN5O_AXdbDAUX428Enhm26KLL0Ew",
    description:
      "An intricately beaded Yoruba Ade crown with symbolic motifs and intact glass beadwork representing royal authority.",
    provenanceHash: "0x3b7f12aa...d8e1",
    dateCreated: "2024-06-01",
    acquiredYear: 2024,
    acquiredMethod: "Direct Acquisition",
    provenance: [
      "Oyo Royal Palace (until c. 1890)",
      "Private Collection, Lagos",
      "Christie's London (1982)",
      "Aduna Gallery (2024)",
    ],
  },
  {
    id: "ART-1104",
    title: "Gold Ashanti Ceremonial Weights",
    culture: "Akan Culture (Ghana)",
    era: "18th Century",
    valuation: 150000,
    status: "Live",
    tier: "Standard",
    imageUrl:
      "https://images.unsplash.com/photo-1590735213920-68192a487bc2?auto=format&fit=crop&q=80",
    description:
      "A set of gold-leaf ceremonial weights used in Akan cultural practices, featuring intricate geometric designs.",
    provenanceHash: "0x5e2c98bb...f3a7",
    dateCreated: "2023-11-10",
    acquiredYear: 2022,
    acquiredMethod: "Gallery Exchange",
    provenance: [
      "Akan Royal Court, Ghana (until 19th Century)",
      "British Colonial Collection (1890–1960)",
      "Private Collection, Zurich (1960–2022)",
      "Aduna Gallery (2022)",
    ],
  },
  {
    id: "ART-2993",
    title: "Ndop Ceremonial King Portrait",
    culture: "Kuba Kingdom (DR Congo)",
    era: "18th Century",
    valuation: 510000,
    status: "Unpublished",
    tier: "Prestige",
    imageUrl:
      "https://images.unsplash.com/photo-1582582621959-48d27397dc69?auto=format&fit=crop&q=80",
    description:
      "A Ndop board depicting a Kuba king in ceremonial regalia, carved with symbolic royal motifs.",
    provenanceHash: "0x1d4e77cc...b92f",
    dateCreated: "2024-02-28",
    acquiredYear: 2023,
    acquiredMethod: "Private Sale",
    provenance: [
      "Kuba Royal Court, DR Congo (until 1920)",
      "Ethnographic Museum, Brussels (1920–1980)",
      "Private Collection, Paris (1980–2023)",
      "Aduna Private Trust (2023)",
    ],
  },
  {
    id: "ART-3301",
    title: "Dogon Tellem Ancestor Figure",
    culture: "Dogon Peoples (Mali)",
    era: "17th Century",
    valuation: 380000,
    status: "Live",
    tier: "Prestige",
    imageUrl:
      "https://images.unsplash.com/photo-1501472312651-726afd116ff1?auto=format&fit=crop&q=80",
    description:
      "An elongated Tellem figure from the Bandiagara Cliffs, placed in cliff granaries to honor ancestors.",
    provenanceHash: "0x6a2f88dd...c1e4",
    dateCreated: "2024-04-12",
    acquiredYear: 2021,
    acquiredMethod: "Private Acquisition",
    provenance: [
      "Tellem Cliff Shrine, Bandiagara, Mali (until c. 1950)",
      "Professor Charles Meyer Field Collection, Basel (1954)",
      "Private Collection, Geneva (1954–2021)",
      "Aduna Gallery (2021)",
    ],
  },
  {
    id: "ART-5587",
    title: "Luba Royal Ceremonial Shield",
    culture: "Luba Empire (DR Congo)",
    era: "19th Century",
    valuation: 275000,
    status: "Live",
    tier: "Standard",
    imageUrl:
      "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&q=80",
    description:
      "A royal shield with painted and woven designs invoking protective spirits, symbol of the king's divine authority.",
    provenanceHash: "0x4c9e22ff...a8b3",
    dateCreated: "2023-09-05",
    acquiredYear: 2019,
    acquiredMethod: "Gallery Exchange",
    provenance: [
      "Luba Royal Court, Katanga Province (until 1910)",
      "Belgian Colonial Collection (1910–1965)",
      "Private Collection, Brussels (1965–2019)",
      "Aduna Gallery (2019)",
    ],
  },
  {
    id: "ART-7744",
    title: "Chokwe Ciooko Divination Pendant",
    culture: "Chokwe Peoples (Angola/DRC)",
    era: "19th Century",
    valuation: 195000,
    status: "Live",
    tier: "Standard",
    imageUrl:
      "https://images.unsplash.com/photo-1569172119333-df9a4a4299b0?auto=format&fit=crop&q=80",
    description:
      "A copper-inlaid divination pendant worn by Chokwe tundao, depicting mythological figures from oral tradition.",
    provenanceHash: "0x8b1a44ee...d2c7",
    dateCreated: "2024-01-20",
    acquiredYear: 2022,
    acquiredMethod: "Auction Acquisition",
    provenance: [
      "Chokwe Diviner, Lunda Norte, Angola (until 1960)",
      "Portuguese Colonial Collection, Luanda (1960–1985)",
      "Private Collection, Lisbon (1985–2022)",
      "Aduna Gallery (2022)",
    ],
  },
  {
    id: "ART-9102",
    title: "Igbo-Ukwu Bronze Vessel",
    culture: "Igbo Culture (Nigeria)",
    era: "9th Century",
    valuation: 2200000,
    status: "Live",
    tier: "VIP",
    imageUrl:
      "https://images.unsplash.com/photo-1600320254374-ce2d293c324e?auto=format&fit=crop&q=80",
    description:
      "An extraordinarily rare 9th-century cast bronze vessel from Igbo-Ukwu, featuring intricate roped decoration and bead motifs.",
    provenanceHash: "0x2f7c99aa...e5d8",
    dateCreated: "2023-07-18",
    acquiredYear: 2023,
    acquiredMethod: "Museum Deaccession",
    provenance: [
      "Igbo-Ukwu Archaeological Site, Nigeria (excavated 1959)",
      "Nigerian National Commission for Museums and Monuments",
      "Deaccessioned via Sotheby's London (2022)",
      "Aduna Private Trust (2023)",
    ],
  },
];

export const INITIAL_ADMIN_COLLECTORS: AdminCollector[] = [
  {
    id: "COL-001",
    name: "E. Sterling",
    email: "e.sterling@sterlingfoundation.org",
    country: "United Kingdom",
    tier: "VIP",
    purchasedValue: 4200000,
    acquisitionsCount: 7,
    amlStatus: "Verified",
    joinedDate: "2022-03-15",
    avatarColor: "#C5A059",
  },
  {
    id: "COL-002",
    name: "J. Rothschild",
    email: "j.rothschild@rothschildart.com",
    country: "Switzerland",
    tier: "VIP",
    purchasedValue: 8900000,
    acquisitionsCount: 12,
    amlStatus: "Verified",
    joinedDate: "2021-08-20",
    avatarColor: "#B35C44",
  },
  {
    id: "COL-003",
    name: "Sheikh Al-Maktoum",
    email: "office@almaktoum-collect.ae",
    country: "UAE",
    tier: "Prestige",
    purchasedValue: 15600000,
    acquisitionsCount: 23,
    amlStatus: "Verified",
    joinedDate: "2020-01-10",
    avatarColor: "#0F0F0F",
  },
  {
    id: "COL-004",
    name: "M. Koffi",
    email: "m.koffi@lagosartgroup.ng",
    country: "Nigeria",
    tier: "Standard",
    purchasedValue: 750000,
    acquisitionsCount: 3,
    amlStatus: "Pending",
    joinedDate: "2024-06-01",
    avatarColor: "#6B8E23",
  },
  {
    id: "COL-005",
    name: "E. Rostova",
    email: "e.rostova@rosfinart.ch",
    country: "Switzerland",
    tier: "Standard",
    purchasedValue: 320000,
    acquisitionsCount: 1,
    amlStatus: "Verified",
    joinedDate: "2025-02-14",
    avatarColor: "#4A6FA5",
  },
  {
    id: "COL-006",
    name: "Museum of African Art, Dakar",
    email: "acquisitions@maa.sn",
    country: "Senegal",
    tier: "VIP",
    purchasedValue: 3100000,
    acquisitionsCount: 5,
    amlStatus: "Verified",
    joinedDate: "2021-11-03",
    avatarColor: "#8B4513",
  },
  {
    id: "COL-007",
    name: "T. Nakamura",
    email: "t.nakamura@tokyofineart.jp",
    country: "Japan",
    tier: "Prestige",
    purchasedValue: 2800000,
    acquisitionsCount: 4,
    amlStatus: "Verified",
    joinedDate: "2023-02-18",
    avatarColor: "#DC143C",
  },
];

export const INITIAL_ESCROW: EscrowTransaction[] = [
  {
    id: "TX-9A81",
    artworkTitle: "Commemorative Oba Head",
    buyerName: "E. Sterling",
    sellerName: "Aduna Private Trust",
    amount: 1350000,
    status: "Held",
    createdDate: "2026-06-05",
    notes: "Awaiting provenance certificate verification from Benin National Commission.",
  },
  {
    id: "TX-3B01",
    artworkTitle: "Gold Ashanti Ceremonial Weights",
    buyerName: "M. Koffi",
    sellerName: "Aduna Gallery",
    amount: 150000,
    status: "Released",
    createdDate: "2026-05-20",
    notes: "Successfully completed. Funds disbursed to seller.",
  },
  {
    id: "TX-7F22",
    artworkTitle: "Ndop Ceremonial King Portrait",
    buyerName: "J. Rothschild",
    sellerName: "Private Estate, Paris",
    amount: 510000,
    status: "Disputed",
    createdDate: "2026-06-08",
    notes: "Buyer initiated dispute due to provenance document discrepancy. Under arbitration.",
  },
  {
    id: "TX-1C44",
    artworkTitle: "Dogon Tellem Ancestor Figure",
    buyerName: "Museum of African Art, Dakar",
    sellerName: "Aduna Gallery",
    amount: 380000,
    status: "Held",
    createdDate: "2026-06-09",
    notes: "Institutional acquisition. Awaiting museum board final approval.",
  },
  {
    id: "TX-5E90",
    artworkTitle: "Igbo-Ukwu Bronze Vessel",
    buyerName: "T. Nakamura",
    sellerName: "Aduna Private Trust",
    amount: 2200000,
    status: "Released",
    createdDate: "2026-04-15",
    notes: "Completed. SWIFT transfer confirmed. Certificate of ownership issued.",
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "log-001",
    user: "Julien D.",
    timestamp: "2026-06-10 14:32:01 UTC",
    action: "Artwork status changed to Live",
    txHash: "0x7f3a...c912",
    signed: true,
  },
  {
    id: "log-002",
    user: "Helena S.",
    timestamp: "2026-06-10 13:15:44 UTC",
    action: "Collector KYC verified for COL-004",
    txHash: "0x2b8e...d456",
    signed: true,
  },
  {
    id: "log-003",
    user: "Julien D.",
    timestamp: "2026-06-10 11:02:18 UTC",
    action: "Escrow TX-9A81 funds locked",
    txHash: "0x9c1f...a738",
    signed: false,
  },
  {
    id: "log-004",
    user: "Admin System",
    timestamp: "2026-06-10 09:45:00 UTC",
    action: "Compliance scan completed for ART-8921",
    txHash: "0x4e6d...b190",
    signed: true,
  },
  {
    id: "log-005",
    user: "Helena S.",
    timestamp: "2026-06-09 16:22:33 UTC",
    action: "New artwork draft created: ART-7512",
    txHash: "0x1a5c...e824",
    signed: true,
  },
  {
    id: "log-006",
    user: "Julien D.",
    timestamp: "2026-06-09 10:08:12 UTC",
    action: "Settings updated: regulatory email changed",
    txHash: "0x8d2b...f567",
    signed: true,
  },
  {
    id: "log-007",
    user: "Julien D.",
    timestamp: "2026-06-08 15:44:09 UTC",
    action: "Escrow TX-7F22 dispute initiated by buyer",
    txHash: "0x3a91...f2c8",
    signed: true,
  },
  {
    id: "log-008",
    user: "Helena S.",
    timestamp: "2026-06-07 11:30:55 UTC",
    action: "New collector enrolled: COL-007 — T. Nakamura",
    txHash: "0x5d7e...a1b9",
    signed: true,
  },
  {
    id: "log-009",
    user: "Admin System",
    timestamp: "2026-06-06 08:00:00 UTC",
    action: "Automated certificate renewal reminder sent to 3 collectors",
    txHash: "0x1f4c...d7e3",
    signed: true,
  },
  {
    id: "log-010",
    user: "Julien D.",
    timestamp: "2026-06-05 17:12:41 UTC",
    action: "Artwork ART-9102 published to Live inventory",
    txHash: "0x8b2a...c5f6",
    signed: false,
  },
];
