import type {
  AdvisorConsultation,
  AdvisorClient,
  AdvisorPlacement,
  AdvisorActivity,
} from "./advisorTypes";

export const INITIAL_CONSULTATIONS: AdvisorConsultation[] = [
  {
    id: "CONS-001",
    clientName: "E. Sterling",
    clientEmail: "e.sterling@sterlingfoundation.org",
    clientPhone: "+44 7700 900000",
    clientInstitution: "Sterling Foundation",
    clientCountry: "United Kingdom",
    clientTier: "VIP",
    topic: "Igbo-Ukwu Bronze Vessel — Provenance Verification",
    date: "2026-06-18",
    timeSlot: "14:00 - 15:30 GMT",
    status: "Confirmed",
    type: "VIDEO",
    notes: "Client requests additional XRF analysis results before finalizing acquisition.",
    rejectionReason: "",
    currentCollection: "West African Bronzes, Igbo-Ukwu collection",
    meetingFormat: "video",
    followUpRequired: true,
    createdAt: "2026-06-15T10:00:00Z",
  },
  {
    id: "CONS-002",
    clientName: "J. Rothschild",
    clientEmail: "j.rothschild@rothschildart.com",
    clientPhone: "+41 22 818 0000",
    clientInstitution: "Rothschild Art Advisory",
    clientCountry: "Switzerland",
    clientTier: "VIP",
    topic: "Private Sale — Ndop King Portrait Acquisition Strategy",
    date: "2026-06-19",
    timeSlot: "10:00 - 11:30 GMT",
    status: "Confirmed",
    type: "IN_PERSON",
    notes: "Discuss arbitration resolution for disputed escrow TX-7F22.",
    rejectionReason: "",
    currentCollection: "Kuba Ndop collection, Central African masks",
    meetingFormat: "in-person",
    followUpRequired: false,
    createdAt: "2026-06-14T08:30:00Z",
  },
  {
    id: "CONS-003",
    clientName: "M. Koffi",
    clientEmail: "m.koffi@lagosartgroup.ng",
    clientPhone: "+234 801 234 5678",
    clientInstitution: "Lagos Art Group",
    clientCountry: "Nigeria",
    clientTier: "Standard",
    topic: "First Acquisition — Benin Bronze Entry-Level Collection",
    date: "2026-06-20",
    timeSlot: "11:00 - 12:00 GMT",
    status: "Pending",
    type: "VIDEO",
    notes: "New collector. Focus on cultural significance and investment potential.",
    rejectionReason: "",
    currentCollection: "",
    meetingFormat: "video",
    followUpRequired: true,
    createdAt: "2026-06-16T14:00:00Z",
  },
  {
    id: "CONS-004",
    clientName: "Sheikh Al-Maktoum",
    clientEmail: "office@almaktoum-collect.ae",
    clientPhone: "+971 4 555 0000",
    clientInstitution: "Al-Maktoum Collection",
    clientCountry: "UAE",
    clientTier: "Prestige",
    topic: "Bulk Acquisition — West African Bronze Portfolio",
    date: "2026-06-15",
    timeSlot: "09:00 - 10:30 GMT",
    status: "Completed",
    type: "IN_PERSON",
    notes: "Presented 4 bronze pieces. Client interested in Oba Head and Ashanti Weights.",
    rejectionReason: "",
    currentCollection: "Pan-African antiquities, 200+ pieces",
    meetingFormat: "in-person",
    followUpRequired: true,
    createdAt: "2026-06-10T09:00:00Z",
  },
];

export const INITIAL_CLIENTS: AdvisorClient[] = [
  {
    id: "CLI-001",
    name: "E. Sterling",
    email: "e.sterling@sterlingfoundation.org",
    tier: "VIP",
    country: "United Kingdom",
    totalSpent: 4200000,
    acquisitionsCount: 7,
    lastContact: "2026-06-15",
    satisfactionScore: 98,
    avatarColor: "#C5A059",
    interests: ["Benin Bronzes", "Yoruba Art", "Investment-grade pieces"],
  },
  {
    id: "CLI-002",
    name: "J. Rothschild",
    email: "j.rothschild@rothschildart.com",
    tier: "VIP",
    country: "Switzerland",
    totalSpent: 8900000,
    acquisitionsCount: 12,
    lastContact: "2026-06-14",
    satisfactionScore: 95,
    avatarColor: "#B35C44",
    interests: ["Kuba Art", "Pre-Columbian", "High-value sculptures"],
  },
  {
    id: "CLI-003",
    name: "Sheikh Al-Maktoum",
    email: "office@almaktoum-collect.ae",
    tier: "Prestige",
    country: "UAE",
    totalSpent: 15600000,
    acquisitionsCount: 23,
    lastContact: "2026-06-15",
    satisfactionScore: 99,
    avatarColor: "#0F0F0F",
    interests: ["West African Bronzes", "Egyptian Antiquities", "Investment portfolios"],
  },
  {
    id: "CLI-004",
    name: "M. Koffi",
    email: "m.koffi@lagosartgroup.ng",
    tier: "Standard",
    country: "Nigeria",
    totalSpent: 750000,
    acquisitionsCount: 3,
    lastContact: "2026-06-10",
    satisfactionScore: 88,
    avatarColor: "#6B8E23",
    interests: ["Nigerian Contemporary", "Nok Terracotta", "Entry-level collectibles"],
  },
  {
    id: "CLI-005",
    name: "Museum of African Art, Dakar",
    email: "acquisitions@maa.sn",
    tier: "VIP",
    country: "Senegal",
    totalSpent: 3100000,
    acquisitionsCount: 5,
    lastContact: "2026-06-12",
    satisfactionScore: 96,
    avatarColor: "#8B4513",
    interests: ["Museum-grade pieces", "Institutional loans", "Cultural heritage"],
  },
  {
    id: "CLI-006",
    name: "T. Nakamura",
    email: "t.nakamura@tokyofineart.jp",
    tier: "Prestige",
    country: "Japan",
    totalSpent: 2800000,
    acquisitionsCount: 4,
    lastContact: "2026-06-08",
    satisfactionScore: 92,
    avatarColor: "#DC143C",
    interests: ["Contemporary African", "Dogon Art", "Investment diversification"],
  },
];

export const INITIAL_PLACEMENTS: AdvisorPlacement[] = [
  {
    id: "PLC-001",
    artworkTitle: "Igbo-Ukwu Bronze Vessel",
    artworkCulture: "Igbo Culture (Nigeria)",
    artworkEra: "9th Century",
    valuation: 2200000,
    clientName: "E. Sterling",
    status: "Under Review",
    commission: 110000,
    proposedDate: "2026-06-10",
    notes: "Client reviewing XRF analysis. Expected decision by June 20.",
    imageUrl: "https://images.unsplash.com/photo-1600320254374-ce2d293c324e?auto=format&fit=crop&q=80",
  },
  {
    id: "PLC-002",
    artworkTitle: "Ndop Ceremonial King Portrait",
    artworkCulture: "Kuba Kingdom (DR Congo)",
    artworkEra: "18th Century",
    valuation: 510000,
    clientName: "J. Rothschild",
    status: "Proposed",
    commission: 25500,
    proposedDate: "2026-06-12",
    notes: "Pending dispute resolution on prior transaction. Recommend waiting.",
    imageUrl: "https://images.unsplash.com/photo-1582582621959-48d27397dc69?auto=format&fit=crop&q=80",
  },
  {
    id: "PLC-003",
    artworkTitle: "Commemorative Oba Head",
    artworkCulture: "Benin Empire (Nigeria)",
    artworkEra: "16th Century",
    valuation: 1350000,
    clientName: "Sheikh Al-Maktoum",
    status: "Accepted",
    commission: 67500,
    proposedDate: "2026-06-05",
    notes: "Client accepted. Escrow TX-9A81 in progress.",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCJ92I1jZERzyaqiKc3FH4C9WCoalLYXn4QtDJIh9ZxMxNszZAyIVEgqplLCo7hV6V2HH7-BoQadYiRfZZ2rRVU2KyFezQYJuPejkEXFZmCocL68oD0FhhmK9qjLDUo_dGaLRJjMVDik4XNPGjB6Oc9qTanNVOjjccILVz6KJ9t75nNkB6_MXRhluItt8QhY_hJT0f1IjvtTbYQtOVAAFWxowRUhcdAARMvXHJ_EcwLFlZ4EPwj2Hy7iJOq7_ZanC7qnp6Kfj7IvA",
  },
  {
    id: "PLC-004",
    artworkTitle: "Gold Ashanti Ceremonial Weights",
    artworkCulture: "Akan Culture (Ghana)",
    artworkEra: "18th Century",
    valuation: 150000,
    clientName: "M. Koffi",
    status: "Proposed",
    commission: 7500,
    proposedDate: "2026-06-14",
    notes: "Entry-level recommendation. Good investment potential for new collector.",
    imageUrl: "https://images.unsplash.com/photo-1590735213920-68192a487bc2?auto=format&fit=crop&q=80",
  },
  {
    id: "PLC-005",
    artworkTitle: "Dogon Tellem Ancestor Figure",
    artworkCulture: "Dogon Peoples (Mali)",
    artworkEra: "17th Century",
    valuation: 380000,
    clientName: "Museum of African Art, Dakar",
    status: "Completed",
    commission: 19000,
    proposedDate: "2026-05-28",
    notes: "Museum acquisition completed. Loan agreement signed.",
    imageUrl: "https://images.unsplash.com/photo-1501472312651-726afd116ff1?auto=format&fit=crop&q=80",
  },
];

export const INITIAL_ADVISOR_ACTIVITY: AdvisorActivity[] = [
  {
    id: "act-001",
    type: "consultation",
    title: "Consultation Completed",
    description: "Video advisory session with Sheikh Al-Maktoum — West African Bronze Portfolio",
    timestamp: "2026-06-15 09:45 UTC",
    icon: "video",
  },
  {
    id: "act-002",
    type: "placement",
    title: "Placement Accepted",
    description: "Commemorative Oba Head accepted by Sheikh Al-Maktoum — Escrow TX-9A81 initiated",
    timestamp: "2026-06-15 10:12 UTC",
    icon: "check",
  },
  {
    id: "act-003",
    type: "client",
    title: "Client Update",
    description: "E. Sterling requested additional XRF analysis for Igbo-Ukwu Bronze Vessel",
    timestamp: "2026-06-15 11:30 UTC",
    icon: "user",
  },
  {
    id: "act-004",
    type: "system",
    title: "Escrow Alert",
    description: "TX-7F22 dispute initiated by J. Rothschild — Ndop King Portrait. Under arbitration.",
    timestamp: "2026-06-14 16:22 UTC",
    icon: "alert",
  },
  {
    id: "act-005",
    type: "consultation",
    title: "Consultation Scheduled",
    description: "Video advisory with T. Nakamura — Contemporary African Sculpture investment",
    timestamp: "2026-06-14 08:00 UTC",
    icon: "calendar",
  },
  {
    id: "act-006",
    type: "placement",
    title: "Placement Proposed",
    description: "Gold Ashanti Ceremonial Weights proposed to M. Koffi — Entry-level recommendation",
    timestamp: "2026-06-14 14:15 UTC",
    icon: "send",
  },
  {
    id: "act-007",
    type: "client",
    title: "Loan Agreement Signed",
    description: "Museum of African Art, Dakar — Dogon Tellem Ancestor Figure 3-month exhibition",
    timestamp: "2026-06-12 15:30 UTC",
    icon: "file",
  },
  {
    id: "act-008",
    type: "system",
    title: "Commission Payout",
    description: "€19,000 commission disbursed for Dogon Tellem Ancestor Figure placement",
    timestamp: "2026-06-12 17:00 UTC",
    icon: "dollar",
  },
];
