import type { ChatThread, SupportTicket } from "./chatTypes";

export const INITIAL_CHAT_THREADS: ChatThread[] = [
  {
    id: "CHAT-001",
    clientName: "Julian Doe",
    clientRole: "collector",
    advisorName: "Dr. Fatima Benali",
    clientUserId: null,
    advisorUserId: null,
    subject: "Igbo-Ukwu Bronze Vessel — Provenance Inquiry",
    status: "active",
    lastMessage: "Thank you for the XRF analysis results. I would like to schedule a call to discuss the findings.",
    lastMessageTime: "2026-06-15 14:30 UTC",
    unreadCount: 2,
    messages: [
      {
        id: "msg-001",
        senderId: "collector-001",
        senderName: "Julian Doe",
        senderRole: "collector",
        text: "Hello Dr. Benali, I am interested in the Igbo-Ukwu Bronze Vessel. Could you provide more details about the provenance verification process?",
        timestamp: "2026-06-14 10:15 UTC",
        read: true,
      },
      {
        id: "msg-002",
        senderId: "advisor-001",
        senderName: "Dr. Fatima Benali",
        senderRole: "advisor",
        text: "Of course, Julian. The Igbo-Ukwu Bronze Vessel has a complete provenance chain dating back to the 1959 archaeological excavation. We have XRF analysis results ready for your review.",
        timestamp: "2026-06-14 11:30 UTC",
        read: true,
      },
      {
        id: "msg-003",
        senderId: "collector-001",
        senderName: "Julian Doe",
        senderRole: "collector",
        text: "That sounds excellent. Could you share the XRF analysis report?",
        timestamp: "2026-06-14 14:00 UTC",
        read: true,
      },
      {
        id: "msg-004",
        senderId: "advisor-001",
        senderName: "Dr. Fatima Benali",
        senderRole: "advisor",
        text: "I have attached the full XRF analysis report. The composition confirms 9th-century bronze casting techniques consistent with Igbo-Ukwu artifacts. Key findings: copper 87.3%, tin 11.2%, lead 1.5%.",
        timestamp: "2026-06-15 09:00 UTC",
        read: true,
      },
      {
        id: "msg-005",
        senderId: "collector-001",
        senderName: "Julian Doe",
        senderRole: "collector",
        text: "Thank you for the XRF analysis results. I would like to schedule a call to discuss the findings.",
        timestamp: "2026-06-15 14:30 UTC",
        read: false,
      },
    ],
  },
  {
    id: "CHAT-002",
    clientName: "Amara Nkosi",
    clientRole: "collector",
    advisorName: "Dr. Fatima Benali",
    clientUserId: null,
    advisorUserId: null,
    subject: "Private Catalogue — Yoruba Crown Acquisition",
    status: "active",
    lastMessage: "The Yoruba Ade Crown is available for private viewing. Would you like to schedule a visit?",
    lastMessageTime: "2026-06-15 11:00 UTC",
    unreadCount: 1,
    messages: [
      {
        id: "msg-010",
        senderId: "collector-002",
        senderName: "Amara Nkosi",
        senderRole: "collector",
        text: "Dr. Benali, I saw the Royal Beaded Crown in the private catalogue. Is it still available?",
        timestamp: "2026-06-14 16:00 UTC",
        read: true,
      },
      {
        id: "msg-011",
        senderId: "advisor-001",
        senderName: "Dr. Fatima Benali",
        senderRole: "advisor",
        text: "Yes, the Yoruba Ade Crown is still available. It is one of our finest pieces with intact glass beadwork. The provenance traces back to the Oyo Royal Palace.",
        timestamp: "2026-06-15 09:30 UTC",
        read: true,
      },
      {
        id: "msg-012",
        senderId: "advisor-001",
        senderName: "Dr. Fatima Benali",
        senderRole: "advisor",
        text: "The Yoruba Ade Crown is available for private viewing. Would you like to schedule a visit?",
        timestamp: "2026-06-15 11:00 UTC",
        read: false,
      },
    ],
  },
  {
    id: "CHAT-003",
    clientName: "Guest Visitor",
    clientRole: "visitor",
    advisorName: "Helena Sterling",
    clientUserId: null,
    advisorUserId: null,
    subject: "General Inquiry — African Art Authentication",
    status: "active",
    lastMessage: "We offer authentication services starting from €500. Would you like to proceed?",
    lastMessageTime: "2026-06-15 13:00 UTC",
    unreadCount: 0,
    messages: [
      {
        id: "msg-020",
        senderId: "visitor-001",
        senderName: "Guest Visitor",
        senderRole: "visitor",
        text: "Hello, I have a Benin Bronze piece that I would like authenticated. What is the process?",
        timestamp: "2026-06-15 10:00 UTC",
        read: true,
      },
      {
        id: "msg-021",
        senderId: "advisor-002",
        senderName: "Helena Sterling",
        senderRole: "advisor",
        text: "We offer authentication services starting from €500. Would you like to proceed?",
        timestamp: "2026-06-15 13:00 UTC",
        read: true,
      },
    ],
  },
];

export const INITIAL_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: "TKT-001",
    clientName: "Julian Doe",
    clientRole: "collector",
    subject: "Certificate Download Issue",
    description: "I am unable to download my acquisition certificate for ART-8921. The download button does not respond.",
    status: "In Progress",
    priority: "Medium",
    createdDate: "2026-06-14",
    lastUpdate: "2026-06-15",
    assignedTo: "Technical Team",
    responses: [
      { author: "Julian Doe", text: "I am unable to download my acquisition certificate for ART-8921.", timestamp: "2026-06-14 09:00 UTC" },
      { author: "Support", text: "We are investigating the issue. Could you provide your browser version?", timestamp: "2026-06-14 10:30 UTC" },
      { author: "Julian Doe", text: "I am using Chrome 125 on macOS.", timestamp: "2026-06-14 11:00 UTC" },
    ],
  },
  {
    id: "TKT-002",
    clientName: "Amara Nkosi",
    clientRole: "collector",
    subject: "Escrow Status Inquiry",
    description: "I would like to know the current status of my escrow transaction TX-9A81.",
    status: "Open",
    priority: "Low",
    createdDate: "2026-06-15",
    lastUpdate: "2026-06-15",
    assignedTo: "Financial Team",
    responses: [
      { author: "Amara Nkosi", text: "I would like to know the current status of my escrow transaction TX-9A81.", timestamp: "2026-06-15 08:00 UTC" },
    ],
  },
  {
    id: "TKT-003",
    clientName: "Dr. Fatima Benali",
    clientRole: "advisor",
    subject: "Consultation Scheduling Conflict",
    description: "Two of my consultations are scheduled at the same time slot on June 20. Need assistance rescheduling.",
    status: "Resolved",
    priority: "High",
    createdDate: "2026-06-13",
    lastUpdate: "2026-06-14",
    assignedTo: "Operations Team",
    responses: [
      { author: "Dr. Fatima Benali", text: "Two of my consultations are scheduled at the same time slot on June 20.", timestamp: "2026-06-13 14:00 UTC" },
      { author: "Support", text: "We have rescheduled the consultation with M. Koffi to June 21 at 11:00 GMT.", timestamp: "2026-06-14 09:00 UTC" },
      { author: "Dr. Fatima Benali", text: "Thank you, that works perfectly.", timestamp: "2026-06-14 09:30 UTC" },
    ],
  },
  {
    id: "TKT-004",
    clientName: "Guest Visitor",
    clientRole: "visitor",
    subject: "Account Registration Help",
    description: "I am trying to register for an account but the form does not accept my email address.",
    status: "Open",
    priority: "Medium",
    createdDate: "2026-06-15",
    lastUpdate: "2026-06-15",
    assignedTo: "Technical Team",
    responses: [
      { author: "Guest Visitor", text: "I am trying to register for an account but the form does not accept my email address.", timestamp: "2026-06-15 12:00 UTC" },
    ],
  },
];
