import type { Artwork } from "./types";

const BLUR = "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMSIgaGVpZ2h0PSIxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxyZWN0IHdpZHRoPSIxIiBoZWlnaHQ9IjEiIGZpbGw9IiNGRkY4RjAiLz48L3N2Zz4=";

export const ARTWORKS: Artwork[] = [
  {
    id: "art-1",
    title: "Ceremonial Fang Reliquary Guardian",
    region: "Central Africa",
    tribe: "Fang",
    material: "Wood",
    period: "Late 19th Century",
    era: "19th Century",
    origin: "Gabon",
    dimensions: "58 cm × 24 cm × 21 cm",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBxXscArJs7jm8fkVlA0HIef3hG7nB9zqwOK7BCT6Qu4klQbMUWYQgZqPNbqpJRq-MwcmGhf4mmYLiUVINuSkXR8rBU8F1ZHRF8wchLVhgPk5iAS5xT3kjYy85IbKAaxp70n1aUl_n6zBrAIntKg2Sp49BQ_UhCYts4FHBnX2N1rN3ZdNIZQ5CPx1Y-T76d-vIAr0xDMJeZ_ubf0t8oewNFH_fr-mVjel_xdJ3NupPP1Ijd0IfN5O_AXdbDAUX428Enhm26KLL0Ew",
    blurDataURL: BLUR,
    label: "Price on Request",
    scarcityIndex: 97,
    preservationStatus: "Exceptional",
    appreciationRate: "9.2% CAGR",
    isHero: false,
    provenance: [
      "Traditional Keeper, Oyem Region, Gabon (until c. 1910)",
      "Collection of Charles Ratton, Paris (acquired 1928)",
      "Private Collection, Brussels (acquired by descent, 1964)",
      "Aduna Gallery, London (consigned 2024)",
    ],
    historicalStory: "This reliquary guardian figure (Eyema Byeri) is a rare sculptural masterpiece of the Fang peoples of Gabon. Positioned atop bark bboxes containing the bones of distinguished ancestors, the guardian stands as a protective sentinel bridging the physical and spiritual realms.",
    investmentThesis: "Fang reliquary guardian figures of this size, rich deep patina, and exceptional lineage represent the peak of investment-grade African art.",
    investment: {
      estimatedValue: 2400000,
      historicalCagr: 9.2,
      yieldIndex: 97,
    },
  },
  {
    id: "art-2",
    title: "Ife Terracotta Head",
    region: "West Africa",
    tribe: "Yoruba",
    material: "Terracotta",
    period: "14th-15th Century",
    era: "500 BC",
    origin: "Kingdom of Ife, Nigeria",
    dimensions: "32 cm × 18 cm × 19 cm",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCKdiuCw_zTP7WHWHB-xQl16JnOkQSri-8ci20nKnR27BCtmwVuwcbwKQIbr9sAAHFv9NYiL4PCGB4-ewMFWqh7AJtgb05jo4DDtZPr3Y9oZHqvI2Af-K3L53NRUz2v71O6aqjDsl0uWhN882QvAtN53NZqRrjYshqHcr4DfCFJJ2CZjzr63Sa4WPzffRH744uT15yF1UP-xw5XfoKjA_UCf2KG91Cj2mhw_EyMNxG6EYYeHWwNoo-KyTIkrXowWo-mtQf0MtOApw",
    blurDataURL: BLUR,
    label: "Price on Request",
    scarcityIndex: 99,
    preservationStatus: "Pristine",
    appreciationRate: "11.1% CAGR",
    isHero: true,
    provenance: [
      "Royal Ancestorial Compound, Ile-Ife, Nigeria (until c. 1934)",
      "Private Collection, Lagos, Nigeria",
      "Sotheby's London, Fine Antiquities Auction (June 1978, Lot 46)",
      "The Harrison Antiquity Fund, New York (acquired 1978)",
      "Aduna Gallery, London (consigned 2023)",
    ],
    historicalStory: "The Kingdom of Ife stood as an artistic and spiritual epicentre of West Africa from the 11th to the 15th century. This terracotta head showcases the breathtaking naturalism that astonished European art historians when first uncovered.",
    investmentThesis: "Terracotta artifacts from medieval Ife are virtually unobtainable. This specimen offers a vanishingly rare gateway for a museum or institutional portfolio seeking absolute historical significance.",
    investment: {
      estimatedValue: 4800000,
      historicalCagr: 11.1,
      yieldIndex: 99,
    },
  },
  {
    id: "art-3",
    title: "Benin Bronze Relief Plaque",
    region: "West Africa",
    tribe: "Benin",
    material: "Bronze",
    period: "16th-17th Century",
    era: "16th Century",
    origin: "Edo State, Nigeria",
    dimensions: "44 cm × 39 cm × 8 cm",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCJ92I1jZERzyaqiKc3FH4C9WCoalLYXn4QtDJIh9ZxMxNszZAyIVEgqplLCo7hV6V2HH7-BoQadYiRfZZ2rRVU2KyFezQYJuPejkEXFZmCocL68oD0FhhmK9qjLDUo_dGaLRJjMVDik4XNPGjB6Oc9qTanNVOjjccILVz6KJ9t75nNkB6_MXRhluItt8QhY_hJT0f1IjvtTbYQtOVAAFWxowRUhcdAARMvXHJ_EcwLFlZ4EPwj2Hy7iJOq7_ZanC7qnp6Kfj7IvA",
    blurDataURL: BLUR,
    label: "Price on Request",
    scarcityIndex: 98,
    preservationStatus: "Exceptional",
    appreciationRate: "12.4% CAGR",
    isHero: false,
    provenance: [
      "Audience Hall of the Oba's Palace, Benin City (until 1897)",
      "General Sir William MacGregor Collection, London (acquired 1899)",
      "Staatliche Museen zu Berlin, Ethnologisches Museum (accessioned 1904, returned via deaccession)",
      "Aduna Private Trust (acquired 2021)",
    ],
    historicalStory: "This cast-bronze plaque depicts a high-ranking chief or warrior in full ceremonial attire, decorated with intensive beadwork and a crown, holding a staff of office.",
    investmentThesis: "Classically cast Benin Bronzes represent the blue-chip core of global antiquities.",
    investment: {
      estimatedValue: 3600000,
      historicalCagr: 12.4,
      yieldIndex: 98,
    },
  },
  {
    id: "art-4",
    title: "Yoruba Ade Crown",
    region: "West Africa",
    tribe: "Yoruba",
    material: "Glass",
    period: "19th Century",
    era: "19th Century",
    origin: "Oyo Empire, Nigeria",
    dimensions: "45 cm × 35 cm × 35 cm",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/56/Beaded_crown_%28ade%29_of_Onijagbo_Obasoro_Alowolodu%2C_Ogoga_of_Ikere%2C_reigned_1890-1928%2C_Yoruba%2C_Ikere%2C_Osun_state%2C_Nigeria%2C_late_19th_century%2C_basketry%2C_beads%2C_cloth_-_Brooklyn_Museum_-_Brooklyn%2C_NY_-_DSC08538.JPG",
    blurDataURL: BLUR,
    label: "Price on Request",
    scarcityIndex: 95,
    preservationStatus: "Excellent",
    appreciationRate: "10.2% CAGR",
    isHero: false,
    provenance: [
      "Oyo Royal Palace (until c. 1890)",
      "Private Collection, Lagos, Nigeria",
      "Christie's London (acquired 1982)",
      "Aduna Gallery, London (consigned 2024)",
    ],
    historicalStory: "This beaded crown represents the pinnacle of Yoruba royal regalia, adorned with intricate glass beadwork and symbolic motifs.",
    investmentThesis: "Yoruba Ade Crowns with intact beadwork are among the most sought-after pieces in African art collecting.",
    investment: {
      estimatedValue: 1800000,
      historicalCagr: 10.2,
      yieldIndex: 95,
    },
  },
  {
    id: "art-5",
    title: "Nok Terracotta Seated Figure",
    region: "West Africa",
    tribe: "Nok",
    material: "Terracotta",
    period: "500 BC - 200 AD",
    era: "500 BC",
    origin: "Kaduna State, Nigeria",
    dimensions: "38 cm × 15 cm × 12 cm",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/27/Africa_Nok_Male_Figure_Kimbell.jpg",
    blurDataURL: BLUR,
    label: 850000,
    scarcityIndex: 94,
    preservationStatus: "Good",
    appreciationRate: "8.7% CAGR",
    isHero: false,
    provenance: [
      "Archaeological site, Kaduna State, Nigeria (excavated c. 1950)",
      "Private Collection, Lagos (1955–1990)",
      "Sotheby's New York (1990)",
      "European Private Collection (1990–2022)",
      "Aduna Gallery (2022)",
    ],
    historicalStory: "The Nok culture produced some of the earliest known figurative sculptures in West Africa. This seated figure displays the characteristic large elliptical eyes and elaborate coiffure that define the Nok aesthetic tradition.",
    investmentThesis: "Nok terracottas are the oldest sculptures in sub-Saharan Africa and command increasing premiums at auction as museum demand grows.",
    investment: {
      estimatedValue: 850000,
      historicalCagr: 8.7,
      yieldIndex: 94,
    },
  },
  {
    id: "art-6",
    title: "Akan Gold Leaf ceremonial Weight",
    region: "West Africa",
    tribe: "Akan",
    material: "Gold",
    period: "18th Century",
    era: "18th Century",
    origin: "Ashanti Kingdom, Ghana",
    dimensions: "8 cm × 6 cm × 4 cm",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/36/Akan_Goldweights.jpg",
    blurDataURL: BLUR,
    label: 150000,
    scarcityIndex: 82,
    preservationStatus: "Excellent",
    appreciationRate: "6.3% CAGR",
    isHero: false,
    provenance: [
      "Ashanti Royal Court, Kumasi, Ghana (until 1896)",
      "British Colonial Officer Collection (1896–1960)",
      "Private Collection, Edinburgh (1960–2020)",
      "Aduna Gallery (2020)",
    ],
    historicalStory: "Gold weights (abrammuo) were used by the Akan people to measure gold dust, the basis of their monetary system. Each weight carries symbolic meaning related to proverbs, history, or social values.",
    investmentThesis: "Akan gold weights combine precious metal value with deep cultural significance. Complete sets with provenance are increasingly rare.",
    investment: {
      estimatedValue: 150000,
      historicalCagr: 6.3,
      yieldIndex: 82,
    },
  },
  {
    id: "art-7",
    title: "Kuba Ndop Royal Portrait Board",
    region: "Central Africa",
    tribe: "Kuba",
    material: "Wood",
    period: "18th Century",
    era: "18th Century",
    origin: "Kuba Kingdom, DR Congo",
    dimensions: "72 cm × 36 cm × 5 cm",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Brooklyn_Museum_61.33_Ndop_Portrait_of_King_Mishe_miShyaang_maMbul_%2810%29.jpg",
    blurDataURL: BLUR,
    label: 510000,
    scarcityIndex: 88,
    preservationStatus: "Good",
    appreciationRate: "7.8% CAGR",
    isHero: false,
    provenance: [
      "Kuba Royal Court, DR Congo (until 1920)",
      "Ethnographic Museum, Brussels (1920–1980)",
      "Private Collection, Paris (1980–2023)",
      "Aduna Private Trust (2023)",
    ],
    historicalStory: "Ndop boards depict the idealized image of Kuba kings, each bearing distinctive royal insignia. They served as mnemonic devices for oral histories of kingship and were never intended as portraits of individuals.",
    investmentThesis: "Kuba Ndop boards are masterpieces of Central African art. Their combination of geometric abstraction and royal symbolism makes them highly prized by collectors.",
    investment: {
      estimatedValue: 510000,
      historicalCagr: 7.8,
      yieldIndex: 88,
    },
  },
  {
    id: "art-8",
    title: "Dogon Tellem Ancestor Figure",
    region: "West Africa",
    tribe: "Dogon",
    material: "Wood",
    period: "16th-17th Century",
    era: "17th Century",
    origin: "Bandiagara Cliffs, Mali",
    dimensions: "62 cm × 14 cm × 11 cm",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Male_Figure_with_Raised_Arms_MET_DP302219.jpg",
    blurDataURL: BLUR,
    label: 380000,
    scarcityIndex: 90,
    preservationStatus: "Good",
    appreciationRate: "8.1% CAGR",
    isHero: false,
    provenance: [
      "Tellem Cliff Shrine, Bandiagara, Mali (until c. 1950)",
      "Professor Charles Meyer Field Collection, Basel (1954)",
      "Private Collection, Geneva (1954–2021)",
      "Aduna Gallery (2021)",
    ],
    historicalStory: "Tellem figures were placed in cliff granaries to honor ancestors of the Dogon people. Their elongated forms and weathered patina reflect centuries of ritual use in the dramatic Bandiagara landscape.",
    investmentThesis: "Pre-1960 Tellem figures with documented field collection provenance are exceptionally rare and represent the pinnacle of Dogon art collecting.",
    investment: {
      estimatedValue: 380000,
      historicalCagr: 8.1,
      yieldIndex: 90,
    },
  },
  {
    id: "art-9",
    title: "Luba Royal Ceremonial Shield",
    region: "Central Africa",
    tribe: "Luba",
    material: "Wood, Raffia, Pigment",
    period: "19th Century",
    era: "19th Century",
    origin: "Luba Empire, DR Congo",
    dimensions: "85 cm × 45 cm × 8 cm",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0b/WLA_brooklynmuseum_Luba_Staff_19th_century_Wood.jpg",
    blurDataURL: BLUR,
    label: 275000,
    scarcityIndex: 85,
    preservationStatus: "Excellent",
    appreciationRate: "7.2% CAGR",
    isHero: false,
    provenance: [
      "Luba Royal Court, Katanga Province (until 1910)",
      "Belgian Colonial Collection (1910–1965)",
      "Private Collection, Brussels (1965–2019)",
      "Aduna Gallery (2019)",
    ],
    historicalStory: "Luba shields served both practical and spiritual purposes, with painted and woven designs invoking protective spirits. The royal shield was a symbol of the king's authority and divine right to rule.",
    investmentThesis: "Luba royal objects with intact raffia and pigment are highly sought after. The combination of textile and woodwork makes them unique in African art.",
    investment: {
      estimatedValue: 275000,
      historicalCagr: 7.2,
      yieldIndex: 85,
    },
  },
  {
    id: "art-10",
    title: "Chokwe Ciooko Divination Pendant",
    region: "Central Africa",
    tribe: "Chokwe",
    material: "Wood, Copper, Beads",
    period: "Late 19th Century",
    era: "19th Century",
    origin: "Chokwe Territory, Angola/DRC",
    dimensions: "22 cm × 16 cm × 6 cm",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Chokwe_Figur_Chibinda_Ilunga_Museum_Rietberg_2007-1.jpg",
    blurDataURL: BLUR,
    label: 195000,
    scarcityIndex: 86,
    preservationStatus: "Good",
    appreciationRate: "6.9% CAGR",
    isHero: false,
    provenance: [
      "Chokwe Diviner, Lunda Norte, Angola (until 1960)",
      "Portuguese Colonial Collection, Luanda (1960–1985)",
      "Private Collection, Lisbon (1985–2022)",
      "Aduna Gallery (2022)",
    ],
    historicalStory: "Ciooko pendants were worn by Chokwe diviners (tundao) as emblems of spiritual authority. Each pendant depicts a mythological figure or scene from Chokwe oral tradition, serving as a focus for divination rituals.",
    investmentThesis: "Chokwe divination objects combine extraordinary sculptural quality with deep spiritual significance. Copper-inlaid examples are especially prized.",
    investment: {
      estimatedValue: 195000,
      historicalCagr: 6.9,
      yieldIndex: 86,
    },
  },
];
