import type { Artwork, ArtLot, Acquisition, Inquiry, SecurityRecord, CollectorProfile, Booking, Certificate, ProvenanceNode } from "./types";

export const ARTWORKS: Artwork[] = [
  {
    id: "fang-guardian",
    title: "Ceremonial Fang Reliquary Guardian",
    region: "Central Africa",
    tribe: "Fang",
    material: "Wood",
    period: "Late 19th Century",
    era: "19th Century",
    origin: "Gabon",
    dimensions: "58 cm × 24 cm × 21 cm",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBxXscArJs7jm8fkVlA0HIef3hG7nB9zqwOK7BCT6Qu4klQbMUWYQgZqPNbqpJRq-MwcmGhf4mmYLiUVINuSkXR8rBU8F1ZHRF8wchLVhgPk5iAS5xT3kjYy85IbKAaxp70n1aUl_n6zBrAIntKg2Sp49BQ_UhCYts4FHBnX2N1rN3ZdNIZQ5CPx1Y-T76d-vIAr0xDMJeZ_ubf0t8oewNFH_fr-mVjel_xdJ3NupPP1Ijd0IfN5O_AXdbDAUX428Enhm26KLL0Ew",
    label: "Price on Request",
    scarcityIndex: 97,
    preservationStatus: "Exceptional",
    appreciationRate: "9.2% CAGR",
    isHero: false,
    provenance: [
      "Traditional Keeper, Oyem Region, Gabon (until c. 1910)",
      "Collection of Charles Ratton, Paris (acquired 1928)",
      "Private Collection, Brussels (acquired by descent, 1964)",
      "Aduna Gallery, London (consigned 2024)",
    ],
    historicalStory: "This reliquary guardian figure (Eyema Byeri) is a rare sculptural masterpiece of the Fang peoples of Gabon. Positioned atop bark bboxes containing the bones of distinguished ancestors, the guardian stands as a protective sentinel bridging the physical and spiritual realms.",
    investmentThesis: "Fang reliquary guardian figures of this size, rich deep patina, and exceptional lineage represent the peak of investment-grade African art.",
    investment: {
      estimatedValue: "€2.4M",
      historicalCagr: 9.2,
      yieldIndex: 97,
    },
  },
  {
    id: "ife-terracotta",
    title: "Ife Terracotta Head",
    region: "West Africa",
    tribe: "Yoruba",
    material: "Terracotta",
    period: "14th-15th Century",
    era: "500 BC",
    origin: "Kingdom of Ife, Nigeria",
    dimensions: "32 cm × 18 cm × 19 cm",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCKdiuCw_zTP7WHWHB-xQl16JnOkQSri-8ci20nKnR27BCtmwVuwcbwKQIbr9sAAHFv9NYiL4PCGB4-ewMFWqh7AJtgb05jo4DDtZPr3Y9oZHqvI2Af-K3L53NRUz2v71O6aqjDsl0uWhN882QvAtN53NZqRrjYshqHcr4DfCFJJ2CZjzr63Sa4WPzffRH744uT15yF1UP-xw5XfoKjA_UCf2KG91Cj2mhw_EyMNxG6EYYeHWwNoo-KyTIkrXowWo-mtQf0MtOApw",
    label: "Price on Request",
    scarcityIndex: 99,
    preservationStatus: "Pristine",
    appreciationRate: "11.1% CAGR",
    isHero: true,
    provenance: [
      "Royal Ancestorial Compound, Ile-Ife, Nigeria (until c. 1934)",
      "Private Collection, Lagos, Nigeria",
      "Sotheby's London, Fine Antiquities Auction (June 1978, Lot 46)",
      "The Harrison Antiquity Fund, New York (acquired 1978)",
      "Aduna Gallery, London (consigned 2023)",
    ],
    historicalStory: "The Kingdom of Ife stood as an artistic and spiritual epicentre of West Africa from the 11th to the 15th century. This terracotta head showcases the breathtaking naturalism that astonished European art historians when first uncovered.",
    investmentThesis: "Terracotta artifacts from medieval Ife are virtually unobtainable. This specimen offers a vanishingly rare gateway for a museum or institutional portfolio seeking absolute historical significance.",
    investment: {
      estimatedValue: "€4.8M",
      historicalCagr: 11.1,
      yieldIndex: 99,
    },
  },
  {
    id: "benin-plaque",
    title: "Benin Bronze Relief Plaque",
    region: "West Africa",
    tribe: "Benin",
    material: "Bronze",
    period: "16th-17th Century",
    era: "16th Century",
    origin: "Edo State, Nigeria",
    dimensions: "44 cm × 39 cm × 8 cm",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCJ92I1jZERzyaqiKc3FH4C9WCoalLYXn4QtDJIh9ZxMxNszZAyIVEgqplLCo7hV6V2HH7-BoQadYiRfZZ2rRVU2KyFezQYJuPejkEXFZmCocL68oD0FhhmK9qjLDUo_dGaLRJjMVDik4XNPGjB6Oc9qTanNVOjjccILVz6KJ9t75nNkB6_MXRhluItt8QhY_hJT0f1IjvtTbYQtOVAAFWxowRUhcdAARMvXHJ_EcwLFlZ4EPwj2Hy7iJOq7_ZanC7qnp6Kfj7IvA",
    label: "Price on Request",
    scarcityIndex: 98,
    preservationStatus: "Exceptional",
    appreciationRate: "12.4% CAGR",
    isHero: false,
    provenance: [
      "Audience Hall of the Oba's Palace, Benin City (until 1897)",
      "General Sir William MacGregor Collection, London (acquired 1899)",
      "Staatliche Museen zu Berlin, Ethnologisches Museum (accessioned 1904, returned via deaccession)",
      "Aduna Private Trust (acquired 2021)",
    ],
    historicalStory: "This cast-bronze plaque depicts a high-ranking chief or warrior in full ceremonial attire, decorated with intensive beadwork and a crown, holding a staff of office.",
    investmentThesis: "Classically cast Benin Bronzes represent the blue-chip core of global antiquities.",
    investment: {
      estimatedValue: "€3.6M",
      historicalCagr: 12.4,
      yieldIndex: 98,
    },
  },
  {
    id: "ade-crown",
    title: "Yoruba Ade Crown",
    region: "West Africa",
    tribe: "Yoruba",
    material: "Glass",
    period: "19th Century",
    era: "19th Century",
    origin: "Oyo Empire, Nigeria",
    dimensions: "45 cm × 35 cm × 35 cm",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBxXscArJs7jm8fkVlA0HIef3hG7nB9zqwOK7BCT6Qu4klQbMUWYQgZqPNbqpJRq-MwcmGhf4mmYLiUVINuSkXR8rBU8F1ZHRF8wchLVhgPk5iAS5xT3kjYy85IbKAaxp70n1aUl_n6zBrAIntKg2Sp49BQ_UhCYts4FHBnX2N1rN3ZdNIZQ5CPx1Y-T76d-vIAr0xDMJeZ_ubf0t8oewNFH_fr-mVjel_xdJ3NupPP1Ijd0IfN5O_AXdbDAUX428Enhm26KLL0Ew",
    label: "Price on Request",
    scarcityIndex: 95,
    preservationStatus: "Excellent",
    appreciationRate: "10.2% CAGR",
    isHero: false,
    provenance: [
      "Oyo Royal Palace (until c. 1890)",
      "Private Collection, Lagos, Nigeria",
      "Christie's London (acquired 1982)",
      "Aduna Gallery, London (consigned 2024)",
    ],
    historicalStory: "This beaded crown represents the pinnacle of Yoruba royal regalia, adorned with intricate glass beadwork and symbolic motifs.",
    investmentThesis: "Yoruba Ade Crowns with intact beadwork are among the most sought-after pieces in African art collecting.",
    investment: {
      estimatedValue: "€1.8M",
      historicalCagr: 10.2,
      yieldIndex: 95,
    },
  },
];

export const AUCTION_LOTS: ArtLot[] = [
  {
    ...ARTWORKS[0],
    description: "A rare Fang reliquary guardian figure with exceptional provenance, originating from the Oyem Region of Gabon.",
    currentBid: 2400000,
    estimate: "€2,000,000 - €3,000,000",
    provenanceType: "Museum-Grade",
    countdownSeconds: 7200,
    region: "Central Africa",
    history: [
      { bidder: "Bidder #472 (Anonymous)", timestamp: "5 min ago", amount: 2400000 },
      { bidder: "Bidder #318", timestamp: "12 min ago", amount: 2300000 },
      { bidder: "Bidder #591 (Anonymous)", timestamp: "18 min ago", amount: 2200000 },
    ],
  },
  {
    ...ARTWORKS[2],
    description: "A magnificent Benin Bronze relief plaque from the 16th century, depicting a high-ranking chief in ceremonial attire.",
    currentBid: 3600000,
    estimate: "€3,000,000 - €4,500,000",
    provenanceType: "Royal Lineage",
    countdownSeconds: 5400,
    region: "West Africa",
    history: [
      { bidder: "Bidder #201", timestamp: "3 min ago", amount: 3600000 },
      { bidder: "Bidder #472 (Anonymous)", timestamp: "9 min ago", amount: 3500000 },
    ],
  },
  {
    ...ARTWORKS[1],
    description: "A breathtaking Ife terracotta head from the medieval Kingdom of Ife, Nigeria.",
    currentBid: 4800000,
    estimate: "€4,000,000 - €6,000,000",
    provenanceType: "Institutional",
    countdownSeconds: 3600,
    region: "West Africa",
    history: [
      { bidder: "Bidder #591 (Anonymous)", timestamp: "2 min ago", amount: 4800000 },
      { bidder: "Bidder #201", timestamp: "7 min ago", amount: 4700000 },
    ],
  },
];

export const ACQUISITIONS: Acquisition[] = [
  {
    id: "acq-001",
    title: "Benin Bronze Head",
    era: "16th Century",
    culture: "Benin",
    imageUrl: ARTWORKS[2].imageUrl,
    estimatedValueEur: 3600000,
    status: "In Vault",
    provenance: ["Oba's Palace, Benin City", "British Expedition 1897", "Private Collection", "Aduna Gallery 2021"],
    description: "Royal Benin Bronze head from the 16th century",
  },
  {
    id: "acq-002",
    title: "Fang Reliquary Guardian",
    era: "19th Century",
    culture: "Fang",
    imageUrl: ARTWORKS[0].imageUrl,
    estimatedValueEur: 2400000,
    status: "In Transit",
    provenance: ["Oyem Region, Gabon", "Charles Ratton, Paris", "Private Collection, Brussels", "Aduna Gallery 2024"],
    description: "Ceremonial Fang reliquary guardian figure",
  },
  {
    id: "acq-003",
    title: "Ife Terracotta Head",
    era: "14th Century",
    culture: "Yoruba",
    imageUrl: ARTWORKS[1].imageUrl,
    estimatedValueEur: 4800000,
    status: "Appraisal Pending",
    provenance: ["Ile-Ife, Nigeria", "Sotheby's London 1978", "Harrison Fund", "Aduna Gallery 2023"],
    description: "Medieval Ife terracotta head",
  },
];

export const INQUIRIES: Inquiry[] = [
  {
    id: "inq-001",
    artworkId: "benin-bronze-head",
    artworkTitle: "Benin Bronze Head",
    artworkOrigin: "Kingdom of Benin (Modern Nigeria)",
    artworkCentury: "16th Century",
    fullName: "Eleanor Vance",
    affiliation: "The Society of Fine Art Antiquities",
    budget: "$1,000,000 - $5,000,000",
    message: "I am writing to express my interest in the upcoming silent acquisition review of this masterpiece.",
    status: "Curator Assigned",
    curatorName: "Dr. Marc-Andre de Vigny",
    timestamp: "June 9, 2026, 9:20 PM",
    messages: [
      {
        id: "msg-1",
        sender: "user",
        content: "I am writing to express my interest in the upcoming silent acquisition review of this masterpiece.",
        timestamp: "9:20 PM",
      },
      {
        id: "msg-2",
        sender: "curator",
        content: "Thank you for contacting the Acquisition Council. We have noted your specified budget range. Dr. Marc-Andre de Vigny has been assigned as your Senior Advisory Curator.",
        timestamp: "9:22 PM",
      },
    ],
  },
];

export const SECURITY_RECORDS: SecurityRecord[] = [
  {
    id: "sec-001",
    artworkTitle: "Benin Bronze Head",
    vaultLocation: "Geneva Freeport - Chamber IV",
    fingerprintId: "FP-BENI-4521",
    smartContractAddress: "0x8fae3199...a4b2 (Aduna Registry V2)",
    lastInspectionDate: "June 9, 2026",
    temperatureHumidity: "20.1 C / 47.8% RH",
    insurancePolicyNumber: "AXA-MUSEUM-24100-M",
  },
  {
    id: "sec-002",
    artworkTitle: "Fang Reliquary Guardian",
    vaultLocation: "Geneva Freeport - Chamber IV",
    fingerprintId: "FP-FANG-7832",
    smartContractAddress: "0x9ca31844...b5c1 (Aduna Registry V2)",
    lastInspectionDate: "June 9, 2026",
    temperatureHumidity: "20.3 C / 46.2% RH",
    insurancePolicyNumber: "AXA-MUSEUM-38912-M",
  },
];

export const COLLECTOR_PROFILE: CollectorProfile = {
  name: "Julian Momeni",
  email: "julian@momeni-invest.ch",
  tier: "Sovereign Collector",
};

export const BOOKINGS: Booking[] = [];

export const CERTIFICATES: Certificate[] = [
  {
    id: "cert-001",
    artworkId: "benin-bronze-head",
    artworkTitle: "Benin Bronze Head",
    issueDate: "2024-01-15",
    expiryDate: "2025-01-15",
    status: "VALID",
    issuer: "Aduna Gallery Authentication Board",
    certificateNumber: "ADUNA-CERT-2024-001",
  },
  {
    id: "cert-002",
    artworkId: "fang-guardian",
    artworkTitle: "Fang Reliquary Guardian",
    issueDate: "2024-03-20",
    expiryDate: "2025-03-20",
    status: "REVIEWING",
    issuer: "Aduna Gallery Authentication Board",
    certificateNumber: "ADUNA-CERT-2024-002",
  },
];

export const PROVENANCE_NODES: ProvenanceNode[] = [
  {
    id: "node-1",
    date: "1897",
    location: "Benin City, Nigeria",
    description: "Original creation at the Royal Court of Benin",
    verified: true,
  },
  {
    id: "node-2",
    date: "1904",
    location: "Berlin, Germany",
    description: "Acquired by Staatliche Museen zu Berlin",
    verified: true,
  },
  {
    id: "node-3",
    date: "1994",
    location: "Zurich, Switzerland",
    description: "Consortium of Fine Arts, Zurich",
    verified: true,
  },
  {
    id: "node-4",
    date: "2021",
    location: "London, UK",
    description: "Aduna Private Trust acquisition",
    verified: true,
  },
];